controllers:
    resource: ../src/Controller/
    type: attribute


blog_list:
    path: /blog
    controller: App\Controller\BlogController::list

app_logout:
    path: /logout
    methods: GET

app_admin_home:
    path: /admin/home
    methods: GET
    controller: App\Controller\AdminController::home


